(global-set-key (kbd "<f7> <f6>") 'multi-term)
(global-set-key (kbd "<f7> 1") 'multi-term-next)
(global-set-key (kbd "<f7> 2") 'multi-term-prev)
(global-set-key (kbd "<f7> <f7>") 'multi-term-dedicated-select)
(global-set-key (kbd "<f7> 7") 'multi-term-dedicated-open)
(global-set-key (kbd "<f7> 8") 'multi-term-dedicated-close)
(global-set-key (kbd "C-h C-f") 'find-function) 
(global-set-key (kbd "C-c i") (lambda () (interactive) (indent-region (point-min) (point-max))))
